version: "3.10"
services:
  bot-daemon:
    build: ..
    command: ["python", "-m", "app.bot.daemon"]
    env_file: ../.env
    restart: always
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis
  scheduler:
    build: ..
    command: ["python", "-m", "app.bot.scheduler"]
    env_file: ../.env
    restart: always
    volumes:
      - ..:/app
    depends_on:
      - db
      - redis
  api:
    build: ..
    command: ["uvicorn", "app.api.server:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file: ../.env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
